// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: franchises.sql

package database

import (
	"context"
	"database/sql"
)

const createFranchise = `-- name: CreateFranchise :one
INSERT INTO franchises (
    id, created_at, updated_at, name, slug, url
) VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    $3,
    $4
)
RETURNING id, created_at, updated_at, name, slug, url
`

type CreateFranchiseParams struct {
	ID   int32
	Name string
	Slug string
	Url  sql.NullString
}

func (q *Queries) CreateFranchise(ctx context.Context, arg CreateFranchiseParams) (Franchise, error) {
	row := q.db.QueryRowContext(ctx, createFranchise,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Url,
	)
	var i Franchise
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Slug,
		&i.Url,
	)
	return i, err
}

const deleteAllFranchises = `-- name: DeleteAllFranchises :exec
DELETE FROM franchises
`

func (q *Queries) DeleteAllFranchises(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllFranchises)
	return err
}
