// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: genres.sql

package database

import (
	"context"
	"database/sql"
)

const createGenre = `-- name: CreateGenre :one
INSERT INTO genres (
    id, created_at, updated_at, name, slug, url
) VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    $3,
    $4
)
RETURNING id, created_at, updated_at, name, slug, url
`

type CreateGenreParams struct {
	ID   int32
	Name string
	Slug sql.NullString
	Url  sql.NullString
}

func (q *Queries) CreateGenre(ctx context.Context, arg CreateGenreParams) (Genre, error) {
	row := q.db.QueryRowContext(ctx, createGenre,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Url,
	)
	var i Genre
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Slug,
		&i.Url,
	)
	return i, err
}

const deleteAllGenres = `-- name: DeleteAllGenres :exec
DELETE FROM genres
`

func (q *Queries) DeleteAllGenres(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllGenres)
	return err
}
